### PR TITLE
Challenges PR

### PR DESCRIPTION
**Pull request by Santboneless**

### CODE REVIEW

**Comment by Santboneless** [comment]
Need to add tests but want to check first if the function is good

**Comment by Santboneless** [comment]
What I did on this PR :
Sending a challenge + receive the challenge + accept a challenge
UI to check all accepted challenges
Testing and initializing challenge progression (storing and retrieving from the database the progression and checking if the challenge is completed or not)

**Comment by Liototo** [comment]
Made a quick update because not having a no-argument constructor for ChallengeProgression made things crash on my end

**Comment by Santboneless** [comment]
You can send a challenge (for the moment regular_step_challenge for demo) then the friend can accept the challenge and it will be displayed on the home screen and you can check all the different challenges that have been accepted

**Pull request merged**
