### PR TITLE
182 save picture to the database with the checkpoint

### PR DESCRIPTION
**Pull request by simoandreani**
While creating the checkpoint, the image bitmap is compressed and converted into a ByteArray which is stored in the Checkpoint data class, together with the checkpoint name and location.
When saving the route on the database, each Checkpoint is first converted into a CheckpointURL which contains the name, location and the imageURL. The latter points to the image since it must be saved separately into the Firebase Storage, and its obtained after uploading the picture.
If the checkpoint has no image, then the imageURL is empty.

Additionally, while following a route, if the user clicks on a checkpoint it will see an image preview (must be improved)

### CODE REVIEW

**Review by Santboneless — COMMENTED** [review]
On my emulator it seems to work fine but there is something that I find quite inintuitive. When you are just checking out the route from a far, you can still interact with the button to try to take the same picture even though you aren't near it yet. Is it possible maybe to make it just show the picture when you are far away and then when you are like close enough you have the button that appears? It might take too much time and is kind of a nitpick so if you feel like it will take too much time then we can skip it!

**Comment by Santboneless** [comment]
Hey @Liototo can you also have a look at this on your device to see if it works with real pictures?

**Comment by Liototo** [comment]
I second what @Santboneless said about the button interaction, but otherwise it works well on my phone!

**Comment by simoandreani** [comment]
> On my emulator it seems to work fine but there is something that I find quite inintuitive. When you are just checking out the route from a far, you can still interact with the button to try to take the same picture even though you aren't near it yet. Is it possible maybe to make it just show the picture when you are far away and then when you are like close enough you have the button that appears? It might take too much time and is kind of a nitpick so if you feel like it will take too much time then we can skip it!

Thanks for the feedback! I will fix this into another PR: Implement checkpoint match button

**Review by NizarBenMohamed — APPROVED** [review]
Nice! It works fine.

Also do not forget about handling conficts and  the format since it does not pass CI yet.

**Pull request merged**
